- name: test gelf_logger
  connection: local
  hosts: localhost
  tasks:
  - name: run gelf_logger
    gelf_logger:
      dest: "tcp://127.0.0.1:12202"
      message: "hello_world"
      full_message: "lorem ipsum"
      host: "{{ ansible_hostname }}"
      level: 1
      fields:
          environment: "test"
          version: "1.0"
    register: testout
  - name: dump testout
    debug: 
      var: testout
